version: 3
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - ./src:/apps/site/src
    environment:
      - NX_APP_NAME=patronage-web-dev
