name: CI unit testing

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Unit tests
        run: |
          yarn test site --coverage
          yarn test features-feedback --coverage
          yarn test shared --coverage
