name: Project Pipeline

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  setup:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Cypress Binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

  build:
    name: Build project
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run @nrwl build check
        run: yarn build

  lint:
    needs: [build, setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get cached modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Lint
        run: yarn lint

  test:
    needs: [build, setup, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get cached modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Unit tests
        run: |
          yarn test site --coverage
          yarn test features-feedback --coverage
          yarn test shared --coverage

  e2e:
    needs: [build, setup, lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: E2e testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get cached modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Cypress Binary
        uses: actions/cache@v2
        id: cache-cypress-binary
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('**/yarn.lock') }}

      - name: E2e
        run: |
          yarn e2e site-e2e --coverage
          yarn e2e features-feedback-e2e --coverage
