name: Preview Deployment

on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    name: Project preview deployment
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
